blank_issues_enabled: false
contact_links:
    - name: â“ Trouble Setting Up Bot?
      url: https://github.com/lymieux/MEE7/wiki
      about: Fret not, we have a guide!
contact_links:
    - name: ğŸ¤– Don't Know Bot Commands?
      url: https://github.com/lymieux/MEE7/wiki
      about: No one does in the beginning!
# 
# todo: proper wiki links